tap "caskroom/cask"
tap "caskroom/drivers"
tap "caskroom/fonts"
tap "caskroom/versions"
tap "go-delve/delve"
tap "homebrew/bundle"
tap "homebrew/command-not-found"
tap "homebrew/completions"
tap "homebrew/core"
tap "homebrew/livecheck"
tap "homebrew/services"
brew "gdbm"
brew "readline"
brew "xz"
brew "python3"
brew "asciinema"
brew "bash"
brew "bash-completion"
brew "brew-cask-completion"
brew "perl"
brew "git"
brew "bundler-completion"
brew "cocoapods"
brew "diff-so-fancy"
brew "libgpg-error"
brew "libassuan"
brew "libksba"
brew "pth"
brew "dirmngr"
brew "docker-completion"
brew "docker-compose-completion"
brew "dos2unix"
brew "libpng"
brew "freetype"
brew "fontconfig"
brew "gd"
brew "gem-completion"
brew "gibo"
brew "gnu-getopt"
brew "git-flow-avh"
brew "git-when-merged"
brew "libusb"
brew "pinentry"
brew "gnupg"
brew "gpg-agent"
brew "libtool"
brew "graphviz"
brew "grunt-completion"
brew "node"
brew "heroku"
brew "hub"
brew "libsodium"
brew "libusb-compat"
brew "libyaml"
brew "makedepend"
brew "mas"
brew "mix-completion"
brew "mongodb"
brew "mono"
brew "mysql"
brew "ncdu"
brew "nmap"
brew "nuget"
brew "open-completion"
brew "pidof"
brew "pinentry-mac"
brew "pip-completion"
brew "pkg-config"
brew "python"
brew "postgresql"
brew "rails-completion"
brew "rake-completion"
brew "ruby"
brew "ruby-completion"
brew "scons"
brew "screen"
brew "spring-completion"
brew "thefuck"
brew "tree"
brew "vim"
brew "wget"
brew "xonsh"
brew "go-delve/delve/delve"
cask "aerial"
cask "appcleaner"
cask "backblaze"
cask "chromium"
cask "docker-edge"
cask "dotnet-sdk"
cask "duet"
cask "emojipedia"
cask "firefox"
cask "jetbrains-toolbox"
cask "megasync"
cask "postman"
cask "shortcat"
cask "suspicious-package"
cask "tunnelbear"
cask "visual-studio-code"
mas "1Blocker", id: 1107421413
mas "Deliveries", id: 924726344
mas "Jumpshare", id: 889922906
mas "Microsoft Remote Desktop", id: 715768417
mas "Monster", id: 942252191
mas "Noizio", id: 928871589
mas "Numbers", id: 409203825
mas "OneDrive", id: 823766827
mas "Pages", id: 409201541
mas "Shazam", id: 897118787
mas "Soulver", id: 413965349
mas "Tumblr", id: 929285034
mas "Web2App", id: 1075797471
mas "Xcode", id: 497799835
