MONITOR basement_ups@localhost 1 upsmon REPLACE_WITH_UPSMON_PASSWORD primary

MINSUPPLIES 1
SHUTDOWNCMD "/sbin/shutdown -h now"
POWERDOWNFLAG /opt/homebrew/var/run/killpower

POLLFREQ 5
POLLFREQALERT 5
HOSTSYNC 15
DEADTIME 15
FINALDELAY 5

RUN_AS_USER REPLACE_WITH_UPSMON_USER
