#!/usr/bin/env zsh

function ghq() {
  if [[ "$1" == "pwd" ]]; then
    if [[ -z "$2" ]]; then
      ROOT_PATH=$(command ghq root)
      echo "$ROOT_PATH"
      return 0
    fi

    REPO_PATHS=($(command ghq list --full-path --exact "$2"))

    if [[ "${#REPO_PATHS[@]}" -eq 0 ]]; then
      echo "ghq: could not find repository '$2'"
      return 1
    elif [[ "${#REPO_PATHS[@]}" -gt 1 ]]; then
      echo "ghq: ambiguous repository name '$2'"
      return 1
    fi

    echo "$REPO_PATHS[1]"
    return 0
  elif [[ "$1" == "cd" ]]; then
    REPO_PATH="$(ghq pwd "$2")"
    cd "$REPO_PATH"
    return 0
  else
    command ghq $*
  fi
}
