#!/usr/bin/env zsh

function sync-clouds() {
  cd ~

  echo "==> Syncing files from iCloud Documents to MEGA..."
  rsync -va --delete --force-delete ./Documents/ /Volumes/Transcend/MEGA/Documents

  echo
  echo "==> Syncing files from iCloud Documents to OneDrive..."
  # OneDrive doesn't like the filenames used inside of Contacts.app archives (`.abbu`)
  # OneDrive doesn't support external drives
  # rsync -va --delete --force-delete --exclude='*.abbu' ./Documents/ /Volumes/Transcend/OneDrive/Documents
}
