#!/usr/bin/env zsh

function vim-plugin {
  ghq cd dotfiles

  if [[ "$1" == "" ]]; then
    echo "vim-plugin: subcommand required"
    return 1
  elif [[ "$1" != "add" ]] && [[ "$1" != "remove" ]]; then
    echo "vim-plugin: unknown subcommand '$1'"
    return 1
  elif [[ "$2" == "" ]]; then
    echo "vim-plugin: repository owner required"
    return 2
  elif [[ "$3" == "" ]]; then
    repo_split=("${(@s|/|)2}") # split by forward slash
    if [[ "${#repo_split[@]}" -ge 2 ]] && [[ -n "$repo_split[2]" ]]; then
      2="$repo_split[1]"
      3="$repo_split[2]"
    else
      echo "vim-plugin: repository name required"
      return 3
    fi
  fi

  local plugin_repo="$2/$3"
  local plugin_path="vim/pack/$2/start/$3"

  if [[ "$1" == "add" ]]; then
    hub submodule add "$plugin_repo" "$plugin_path"
  elif [[ "$1" == "remove" ]]; then
    git submodule deinit -f "./$plugin_path"
    rm -rf "./.git/modules/$plugin_path"
    git rm -rf "./$plugin_path"
  fi
}
