#!/usr/bin/env zsh

function vim-plugin {
  ghq cd dotfiles

  if [[ "$1" == "" ]]; then
    echo "vim-plugin: subcommand required"
    return 1
  elif [[ "$1" != "add" ]] && [[ "$1" != "remove" ]]; then
    echo "vim-plugin: unknown subcommand '$1'"
    return 1
  elif [[ "$2" == "" ]]; then
    echo "vim-plugin: repository owner required"
    return 2
  elif [[ "$3" == "" ]]; then
    repo_split=("${(@s|/|)2}") # split by forward slash
    if [[ "${#repo_split[@]}" -ge 2 ]] && [[ -n "$repo_split[2]" ]]; then
      2="$repo_split[1]"
      3="$repo_split[2]"
    else
      echo "vim-plugin: repository name required"
      return 3
    fi
  fi

  local plugin_repo="https://github.com/$2/$3.git"
  local plugin_path="$HOME/.vim/pack/$2/start/$3"

  if [[ "$1" == "add" ]]; then
    echo "$plugin_repo" >> ./Vimfile
    plugins="$(cat ./Vimfile | sort | uniq)"
    echo "$plugins" > ./Vimfile

    if [ -d "$plugin_path" ]; then
      git -C "$plugin_path" pull 
    else
      mkdir -p "$plugin_path"
      git clone "$plugin_repo" "$plugin_path"
    fi
  elif [[ "$1" == "remove" ]]; then
    rm -rf "$plugin_path"

    plugins="$(cat ./Vimfile | grep -v "$plugin_repo")"
    echo "$plugins" > ./Vimfile
  fi
}
