#! /usr/bin/env bash

function __color_log() {
  local message=$2
  if [[ -t 1 ]] && tput colors &> /dev/null; then
    local message="\033[${1}m${2}\033[0m"
  fi
  echo -e "$message"
}

while ! xcode-select --print-path &> /dev/null; do
  xcode-select --install &> /dev/null
  __color_log 94 'Waiting for Xcode Command Line Developer Tools installation'
  __color_log 94 '(Select "Install" in the "Install Command Line Developer Tools" prompt)'
  sleep 15
done

__color_log 92 "Xcode or Xcode Command Line Developer Tools are installed at $(xcode-select --print-path)"

if [[ -z "$SELECTED_FOLDER" ]]; then
  DEFAULT_FOLDER=$HOME/.dotfiles
  read -r -p "Directory to clone to: ($DEFAULT_FOLDER) " SELECTED_FOLDER
  SELECTED_FOLDER=${SELECTED_FOLDER:-$DEFAULT_FOLDER}
fi
SELECTED_FOLDER=${SELECTED_FOLDER/#\~/$HOME}

if [[ -e $SELECTED_FOLDER ]]; then
  __color_log 91 "fatal: cannot clone to existing local directory"
  exit 1
fi

if [[ -z "$SELECTED_REPO" ]]; then
  DEFAULT_REPO="https://github.com/jarrodldavis/dotfiles.git"
  read -r -p "Repository to clone from: ($DEFAULT_REPO) " SELECTED_REPO
  SELECTED_REPO=${SELECTED_REPO:-$DEFAULT_REPO}
fi

__color_log 92 "Cloning from $SELECTED_REPO into $SELECTED_FOLDER"

if ! git clone "$SELECTED_REPO" "$SELECTED_FOLDER"; then
  __color_log 91 "fatal: could not clone dotfiles directory"
  exit 2
fi

if ! cd "$SELECTED_FOLDER"; then
  __color_log 91 "fatal: could not change to local dotfiles directory"
  exit 3
fi

./install/core
