#!/usr/bin/env bash

set -e

BASH_CONFIG="install/bash.yaml"
CONFIG="install/conf.yaml"
DOTBOT_DIR="dotbot"
DOTBOT_BIN="bin/dotbot"
BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/.."
DOTBOT_PATH="${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}"

cd "${BASEDIR}"

function __color_log() {
  local message=$2
  if [[ -t 1 ]] && tput colors &> /dev/null; then
    local message="\033[${1}m${2}\033[0m"
  fi
  echo -e "$message"
}

while ! xcode-select --print-path &> /dev/null; do
  xcode-select --install &> /dev/null
  __color_log 94 'Waiting for Xcode Command Line Developer Tools installation'
  __color_log 94 '(Select "Install" in the "Install Command Line Developer Tools" prompt)'
  sleep 15
done

__color_log 92 "Xcode or Xcode Command Line Developer Tools are installed at $(xcode-select --print-path)"

git submodule update --init --recursive

$DOTBOT_PATH -d "${BASEDIR}" --plugin-dir dotbot-brew -c "${BASH_CONFIG}"
bash -l -c "\"$DOTBOT_PATH\" -d \"${BASEDIR}\" --plugin-dir dotbot-brew -c \"${CONFIG}\""

# Check for updated bash
if [[ "$SHELL" != "$(command -v bash)" ]]; then
  __color_log 95 "A new installation of bash was installed via Homebrew."
  # force exit of old shell
  kill -SIGUSR1 $PPID
elif [[ "$BASH_VERSION" != "$(bash -c 'echo $BASH_VERSION')" ]]; then
  __color_log 95 "A new version of bash was updated via Homebrew."
  # force exit of old shell
  kill -SIGUSR1 $PPID
fi
