[Service]
ExecStart=
ExecStart=/usr/bin/systemd-inhibit --what=sleep --mode=block \
    --who=Snapper --why="Snapshot cleanup and Btrfs quota maintenance" \
    /usr/libexec/snapper/systemd-helper --cleanup
