#! /usr/bin/env bash

while ! xcode-select --print-path &> /dev/null; do
  xcode-select --install &> /dev/null
  echo 'Waiting for Xcode Command Line Developer Tools installation'
  echo '(Select "Install" in the "Install Command Line Developer Tools" prompt)'
  sleep 15
done

echo "Xcode or Xcode Command Line Developer Tools are installed at $(xcode-select --print-path)"

DEFAULT_FOLDER=$HOME/.dotfiles
read -r -p "Directory to clone to: ($DEFAULT_FOLDER) " SELECTED_FOLDER
SELECTED_FOLDER=${SELECTED_FOLDER:-$DEFAULT_FOLDER}
SELECTED_FOLDER=${SELECTED_FOLDER/#\~/$HOME}

if [[ -e $SELECTED_FOLDER ]]; then
  echo "fatal: cannot clone to existing local directory"
  exit 1
fi

DEFAULT_REPO="https://github.com/jarrodldavis/dotfiles.git"
read -r -p "Repository to clone from: ($DEFAULT_REPO) " SELECTED_REPO
SELECTED_REPO=${SELECTED_REPO:-$DEFAULT_REPO}

echo "Cloning from $SELECTED_REPO into $SELECTED_FOLDER"

if ! git clone "$SELECTED_REPO" "$SELECTED_FOLDER"; then
  echo "fatal: could not clone dotfiles directory"
  exit 1
fi

if ! cd "$SELECTED_FOLDER"; then
  echo "fatal: could not change to local dotfiles directory"
  exit 2
fi

./install
