#! /usr/bin/env bash

scripts_dir=$(dirname "$0")
cd "$scripts_dir" || exit

real_scripts_dir=$(pwd -P)
dotfiles_dir="$real_scripts_dir/.."
cd "$dotfiles_dir" || exit

brew bundle dump --force
code --list-extensions > vscode/extensions.txt
npm ls -g --depth 0 --json --update-notifier false | jq -r '.dependencies | keys | .[]' > npm-globals.txt

HEROKU_PLUGINS=$(heroku plugins)
if [[ "$HEROKU_PLUGINS" == "no plugins installed" ]]; then
  echo > heroku-plugins.txt # empty file
else
  cut -d' ' -f1 <<< "$HEROKU_PLUGINS" > heroku-plugins.txt
fi

rbenv versions --bare > rbenv/versions.txt

cargo install-update -al | tail -n +4 | cut -f1 -d' ' -s > cargo-bins.txt
