#!/usr/bin/env bash

set -e

DOWNLOAD_URL="https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip"
DOWNLOAD_PATH="$(mktemp -d)/ngrok.zip"
curl -fsSL "$DOWNLOAD_URL" -o "$DOWNLOAD_PATH"

INSTALL_DIR="/opt/ngrok.com/ngrok/"
sudo mkdir -pv "$INSTALL_DIR"

sudo unzip "$DOWNLOAD_PATH" -d "$INSTALL_DIR"
sudo ln -sfv "$INSTALL_DIR/ngrok" /usr/local/bin

ngrok update --log stdout --log-level debug
